# Generated by Django 3.2.10 on 2021-12-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(blank=True, default="Let's talk business!", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'title')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('avatar', models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/messaging-a9715.appspot.com/o/avatars%2Fdefault.png?alt=media&token=6ad7965e-9653-493f-b6c8-364d17594356')),
                ('about', models.TextField(blank=True, default='Here I am using the messaging app!', max_length=150)),
                ('is_online', models.BooleanField(blank=True, default=False)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reciever_id', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('TEXT', 'text'), ('VIDEO', 'video'), ('AUDIO', 'audio')], default='text', max_length=25)),
                ('msg_type', models.CharField(choices=[('DEFAULT', 'default'), ('COMMENT', 'comment')], default='default', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciever_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='message.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.userprofile')),
            ],
            options={
                'unique_together': {('user', 'club')},
            },
        ),
    ]
